// ⚠️ MINH HỌA - thay bằng data thật khi launch (Firestore)
// Dữ liệu cộng đồng demo - dùng khi chưa có Firebase config thật.
// Khi cắm config thật, firestore-ops.ts sẽ đọc/ghi Firestore thay vì mảng này.

export interface DemoUser {
  uid: string;
  displayName: string;
  photoURL?: string;
  createdAt: string;
  points: number;
  role: "member" | "ai" | "mod";
}

export interface DemoAnswer {
  id: string;
  body: string;
  authorUid: string;
  authorName: string;
  createdAt: string;
  upvotes: number;
  upvoterUids: string[];
  isAccepted: boolean;
  isAI: boolean;
  flagged: boolean;
}

export interface DemoPost {
  id: string;
  title: string;
  body: string;
  tags: string[];
  authorUid: string;
  authorName: string;
  createdAt: string;
  upvotes: number;
  upvoterUids: string[];
  answerCount: number;
  solvedAnswerId: string | null;
  flagged: boolean;
  answers: DemoAnswer[];
}

export const demoUsers: DemoUser[] = [
  {
    uid: "u-trang",
    displayName: "Trang",
    createdAt: "2026-09-01",
    points: 340,
    role: "member",
  },
  {
    uid: "u-minh",
    displayName: "Minh",
    createdAt: "2026-09-02",
    points: 210,
    role: "member",
  },
  {
    uid: "u-lan",
    displayName: "Lan",
    createdAt: "2026-09-03",
    points: 180,
    role: "member",
  },
  {
    uid: "u-huy",
    displayName: "Huy",
    createdAt: "2026-09-04",
    points: 90,
    role: "member",
  },
  {
    uid: "u-mai",
    displayName: "Mai",
    createdAt: "2026-09-05",
    points: 260,
    role: "member",
  },
  {
    uid: "u-duc",
    displayName: "Đức",
    createdAt: "2026-09-06",
    points: 150,
    role: "member",
  },
  {
    uid: "u-thao",
    displayName: "Thảo",
    createdAt: "2026-09-07",
    points: 320,
    role: "member",
  },
  {
    uid: "u-quang",
    displayName: "Quang",
    createdAt: "2026-09-08",
    points: 75,
    role: "member",
  },
  {
    uid: "u-ngan",
    displayName: "Ngân",
    createdAt: "2026-09-09",
    points: 120,
    role: "member",
  },
  {
    uid: "u-linh",
    displayName: "Linh",
    createdAt: "2026-09-10",
    points: 205,
    role: "member",
  },
  {
    uid: "u-tuan",
    displayName: "Tuấn",
    createdAt: "2026-09-11",
    points: 60,
    role: "member",
  },
  {
    uid: "u-huong",
    displayName: "Hương",
    createdAt: "2026-09-12",
    points: 95,
    role: "member",
  },
  {
    uid: "u-nam",
    displayName: "Nam",
    createdAt: "2026-09-13",
    points: 140,
    role: "member",
  },
  {
    uid: "u-phuong",
    displayName: "Phương",
    createdAt: "2026-09-14",
    points: 185,
    role: "member",
  },
  {
    uid: "ai-friday",
    displayName: "Friday (AI)",
    createdAt: "2026-09-01",
    points: 0,
    role: "ai",
  },
];

export const demoPosts: DemoPost[] = [
  {
    id: "p-1",
    title: "Hermes Agent có miễn phí không? Tôi dùng thử cần trả tiền gì?",
    body: "Mình mới nghe về Hermes Agent, không rõ phần mềm có miễn phí không, hay phải trả phí theo tháng? Nếu phải trả thì trả cho cái gì?",
    tags: ["cài đặt", "chi phí"],
    authorUid: "u-trang",
    authorName: "Trang",
    createdAt: "2026-09-08",
    upvotes: 12,
    upvoterUids: ["u-minh", "u-lan"],
    answerCount: 2,
    solvedAnswerId: "a-1",
    flagged: false,
    answers: [
      {
        id: "a-1",
        body: 'Phần mềm Hermes Agent miễn phí 100%. Bạn chỉ trả tiền cho AI model mình dùng, tính theo số token đã dùng - dùng ít trả ít, dùng nhiều trả nhiều, không gói tháng. Chi tiết mình đã viết ở bài "Thanh toán từ Việt Nam".',
        authorUid: "ai-friday",
        authorName: "Friday (AI)",
        createdAt: "2026-09-08",
        upvotes: 8,
        upvoterUids: ["u-trang"],
        isAccepted: true,
        isAI: true,
        flagged: false,
      },
      {
        id: "a-2",
        body: "Mình không biết code vẫn dùng bình thường nha, cài như phần mềm thường thôi. Còn tiền thì đúng là chỉ trả theo cái mình dùng, không bị đóng gói tháng gì cả.",
        authorUid: "u-minh",
        authorName: "Minh",
        createdAt: "2026-09-09",
        upvotes: 3,
        upvoterUids: [],
        isAccepted: false,
        isAI: false,
        flagged: false,
      },
    ],
  },
  {
    id: "p-2",
    title:
      "Không biết code có dùng được không? Tôi chỉ quen dùng Facebook, Zalo",
    body: "Mình hoàn toàn không biết gì về lập trình. Hermes Agent có cần gõ lệnh hay cấu hình gì phức tạp không?",
    tags: ["người mới"],
    authorUid: "u-lan",
    authorName: "Lan",
    createdAt: "2026-09-10",
    upvotes: 9,
    upvoterUids: ["u-trang"],
    answerCount: 2,
    solvedAnswerId: "a-3",
    flagged: false,
    answers: [
      {
        id: "a-3",
        body: 'Được, hoàn toàn không cần biết code. Bản Desktop cài như phần mềm thường, mọi thao tác qua giao diện bấm chuột. Trang Cộng Đồng AI viết riêng cho người không chuyên, bạn bắt đầu từ bài "Hermes Agent là gì" nhé.',
        authorUid: "ai-friday",
        authorName: "Friday (AI)",
        createdAt: "2026-09-10",
        upvotes: 6,
        upvoterUids: [],
        isAccepted: true,
        isAI: true,
        flagged: false,
      },
      {
        id: "a-6",
        body: "Mình cũng chỉ biết dùng Facebook thôi, cài Hermes xong toàn chat bằng tiếng Việt, nó chỉ từng bước. Yên tâm nha chị Lan.",
        authorUid: "u-thao",
        authorName: "Thảo",
        createdAt: "2026-09-11",
        upvotes: 2,
        upvoterUids: [],
        isAccepted: false,
        isAI: false,
        flagged: false,
      },
    ],
  },
  {
    id: "p-3",
    title: "Sao không thấy hướng dẫn kết nối Zalo hoặc Telegram?",
    body: "Mình muốn Hermes gửi tin nhắn qua Zalo hoặc Telegram cho tiện, nhưng tìm mãi không thấy hướng dẫn.",
    tags: ["kết nối"],
    authorUid: "u-huy",
    authorName: "Huy",
    createdAt: "2026-09-12",
    upvotes: 5,
    upvoterUids: [],
    answerCount: 2,
    solvedAnswerId: null,
    flagged: false,
    answers: [
      {
        id: "a-4",
        body: "Telegram hiện bị chặn tại Việt Nam, còn Zalo chưa được Hermes hỗ trợ chính thức. Với người dùng VN, chat thẳng trong app Desktop là cách ổn định nhất. Xem giải thích chi tiết trong mục Hỏi đáp trên trang chủ.",
        authorUid: "ai-friday",
        authorName: "Friday (AI)",
        createdAt: "2026-09-12",
        upvotes: 2,
        upvoterUids: [],
        isAccepted: false,
        isAI: true,
        flagged: false,
      },
      {
        id: "a-30",
        body: "Mình cũng tính vậy nhưng nghe nói Telegram chặn thì bỏ luôn. Giờ mình để Hermes gửi email tổng hợp mỗi sáng thay thế, cũng ổn áp không thua gì.",
        authorUid: "u-mai",
        authorName: "Mai",
        createdAt: "2026-09-13",
        upvotes: 3,
        upvoterUids: [],
        isAccepted: false,
        isAI: false,
        flagged: false,
      },
    ],
  },
  {
    id: "p-4",
    title: "Thanh toán từ Việt Nam cần thẻ gì? Visa debit có được không?",
    body: "Mình có thẻ Visa debit của ngân hàng Việt Nam, thanh toán được không, hay bắt buộc thẻ tín dụng?",
    tags: ["chi phí", "thanh toán"],
    authorUid: "u-minh",
    authorName: "Minh",
    createdAt: "2026-09-13",
    upvotes: 4,
    upvoterUids: [],
    answerCount: 2,
    solvedAnswerId: "a-5",
    flagged: false,
    answers: [
      {
        id: "a-5",
        body: "Thẻ Visa debit quốc tế dùng được bình thường bạn nhé, không cần thẻ tín dụng. Quan trọng là thẻ đã bật thanh toán online quốc tế (gọi tổng đài ngân hàng để mở nếu chưa). Nạp trước một khoản nhỏ để thử trước là an tâm nhất.",
        authorUid: "ai-friday",
        authorName: "Friday (AI)",
        createdAt: "2026-09-13",
        upvotes: 7,
        upvoterUids: ["u-minh"],
        isAccepted: true,
        isAI: true,
        flagged: false,
      },
      {
        id: "a-7",
        body: 'Mình xài thẻ debit của Vietcombank được luôn. Chỉ cần bật "thanh toán online" trong app là xong, nạp ít tiền thôi đừng nạp nhiều.',
        authorUid: "u-duc",
        authorName: "Đức",
        createdAt: "2026-09-13",
        upvotes: 4,
        upvoterUids: [],
        isAccepted: false,
        isAI: false,
        flagged: false,
      },
    ],
  },
  {
    id: "p-5",
    title: 'Cài trên Windows báo "Windows protected your PC" thì làm sao?',
    body: 'Mình tải Hermes Desktop về, lúc bấm cài thì Windows hiện cảnh báo xanh "Windows protected your PC" không cho chạy. Như vậy có phải file bị virus không, và làm sao để cài tiếp?',
    tags: ["cài đặt"],
    authorUid: "u-mai",
    authorName: "Mai",
    createdAt: "2026-09-14",
    upvotes: 15,
    upvoterUids: ["u-lan", "u-huy", "u-nam"],
    answerCount: 2,
    solvedAnswerId: "a-8",
    flagged: false,
    answers: [
      {
        id: "a-8",
        body: 'Đây là cảnh báo SmartScreen của Windows, vì Hermes chưa có chữ ký số trả phí chứ không phải virus. Bạn bấm "More info" rồi bấm "Run anyway" là chạy được. Nhớ tải đúng bản từ trang chính thức của Nous Research để chắc chắn an toàn.',
        authorUid: "ai-friday",
        authorName: "Friday (AI)",
        createdAt: "2026-09-14",
        upvotes: 11,
        upvoterUids: ["u-mai"],
        isAccepted: true,
        isAI: true,
        flagged: false,
      },
      {
        id: "a-9",
        body: 'Mình cũng dính cái này, sợ muốn chết. Ai chỉ cho cái nút "More info" là xong liền. Lần đầu ai cũng hoảng vậy đó.',
        authorUid: "u-lan",
        authorName: "Lan",
        createdAt: "2026-09-14",
        upvotes: 5,
        upvoterUids: [],
        isAccepted: false,
        isAI: false,
        flagged: false,
      },
    ],
  },
  {
    id: "p-6",
    title:
      "Thẻ Visa của mình không nạp được OpenRouter, có cách nào khác không?",
    body: "Mình thử nạp tiền cho OpenRouter mà thẻ báo lỗi giao dịch không thành công, thử 2 lần vẫn không được. Có cách thanh toán nào khác cho người Việt Nam không?",
    tags: ["thanh toán"],
    authorUid: "u-huong",
    authorName: "Hương",
    createdAt: "2026-09-15",
    upvotes: 8,
    upvoterUids: ["u-minh"],
    answerCount: 2,
    solvedAnswerId: null,
    flagged: false,
    answers: [
      {
        id: "a-10",
        body: "Thường có 3 nguyên nhân: thẻ chưa bật thanh toán online quốc tế, ngân hàng chặn giao dịch nước ngoài, hoặc hết hạn mức. Bạn thử gọi tổng đài ngân hàng xác nhận bật thanh toán quốc tế trước, rồi nạp lại. Nếu vẫn lỗi, dùng thẻ khác hoặc thẻ ảo (virtual card) cũng là một lựa chọn.",
        authorUid: "ai-friday",
        authorName: "Friday (AI)",
        createdAt: "2026-09-15",
        upvotes: 6,
        upvoterUids: [],
        isAccepted: false,
        isAI: true,
        flagged: false,
      },
      {
        id: "a-11",
        body: 'Mình từng bị y chang, hoá ra là thẻ chưa bật "giao dịch online". Vào app ngân hàng bật lên là nạp được ngay.',
        authorUid: "u-trang",
        authorName: "Trang",
        createdAt: "2026-09-15",
        upvotes: 4,
        upvoterUids: [],
        isAccepted: false,
        isAI: false,
        flagged: false,
      },
    ],
  },
  {
    id: "p-7",
    title: "Máy mình yếu (8GB RAM) có chạy Hermes nổi không mọi người?",
    body: "Laptop mình cũ, chỉ có 8GB RAM, i3 thôi. Mình sợ tải về không chạy nổi hoặc chạy giật lag. Ai đã chạy trên máy yếu cho mình xin ý kiến.",
    tags: ["phần cứng"],
    authorUid: "u-nam",
    authorName: "Nam",
    createdAt: "2026-09-16",
    upvotes: 10,
    upvoterUids: ["u-quang", "u-duc"],
    answerCount: 2,
    solvedAnswerId: null,
    flagged: false,
    answers: [
      {
        id: "a-12",
        body: "Chạy được bạn ơi. Bản Desktop khá nhẹ, phần nặng nằm ở phía model AI (chạy trên server, không tốn RAM máy bạn nhiều). 8GB dùng mượt cho các việc thường: tóm tắt tin, viết email, hỏi đáp. Cứ tải về thử, không hài lòng thì gỡ, không mất gì.",
        authorUid: "u-quang",
        authorName: "Quang",
        createdAt: "2026-09-16",
        upvotes: 8,
        upvoterUids: ["u-nam"],
        isAccepted: false,
        isAI: false,
        flagged: false,
      },
      {
        id: "a-13",
        body: "Mình chạy trên laptop i3 8GB vẫn ổn. Chỉ lưu ý đóng bớt tab trình duyệt khi chạy để máy thoáng hơn là được.",
        authorUid: "u-duc",
        authorName: "Đức",
        createdAt: "2026-09-16",
        upvotes: 3,
        upvoterUids: [],
        isAccepted: false,
        isAI: false,
        flagged: false,
      },
    ],
  },
  {
    id: "p-8",
    title: "Muốn Hermes tự gửi bản tin 6h30 mỗi sáng thì cài ở đâu?",
    body: "Mình thấy nhiều người khoe Hermes tự tổng hợp tin tức gửi mỗi sáng. Mình muốn làm vậy thì bắt đầu từ đâu? Có cần biết lập trình không?",
    tags: ["sử dụng", "kỹ năng"],
    authorUid: "u-thao",
    authorName: "Thảo",
    createdAt: "2026-09-17",
    upvotes: 13,
    upvoterUids: ["u-lan", "u-mai"],
    answerCount: 3,
    solvedAnswerId: "a-14",
    flagged: false,
    answers: [
      {
        id: "a-14",
        body: 'Không cần biết code. Cách dễ nhất là mở Hermes và nói: "Mỗi sáng 6h30 tự tổng hợp tin tức công nghệ và gửi cho mình". Hermes sẽ tự tạo lịch và làm việc. Trong Thư viện cũng có sẵn skill "Bản tin sáng tự động" kèm hướng dẫn chỉnh nguồn tin theo gu của bạn, tải về nạp vào là dùng.',
        authorUid: "ai-friday",
        authorName: "Friday (AI)",
        createdAt: "2026-09-17",
        upvotes: 12,
        upvoterUids: ["u-thao"],
        isAccepted: true,
        isAI: true,
        flagged: false,
      },
      {
        id: "a-15",
        body: "Mình làm được rồi nè, chỉ cần nói bằng tiếng Việt tự nhiên là nó tự đặt lịch luôn. Sáng nào cũng có bản tin, đỡ phải tự lướt.",
        authorUid: "u-lan",
        authorName: "Lan",
        createdAt: "2026-09-17",
        upvotes: 5,
        upvoterUids: [],
        isAccepted: false,
        isAI: false,
        flagged: false,
      },
      {
        id: "a-16",
        body: 'Bạn nhớ để máy mở sẵn (hoặc để Hermes chạy nền) vào giờ đó nó mới chạy được nhé. Đặt xong thử nói "chạy thử bây giờ" để kiểm tra luôn.',
        authorUid: "u-minh",
        authorName: "Minh",
        createdAt: "2026-09-17",
        upvotes: 3,
        upvoterUids: [],
        isAccepted: false,
        isAI: false,
        flagged: false,
      },
    ],
  },
  {
    id: "p-9",
    title: "Chia sẻ: mình dùng Hermes quản lý đơn hàng shop hoa thế nào",
    body: "Mình bán hoa online, ngày nào cũng ngập trong tin nhắn hỏi giá, đặt hàng. Mình đã nhờ Hermes soạn bộ câu trả lời mẫu và nhắc đơn nào chưa hồi âm. Chia sẻ cho ai cũng đang bán hàng online.",
    tags: ["kinh doanh"],
    authorUid: "u-huong",
    authorName: "Hương",
    createdAt: "2026-09-18",
    upvotes: 18,
    upvoterUids: ["u-lan", "u-mai", "u-thao", "u-trang"],
    answerCount: 2,
    solvedAnswerId: null,
    flagged: false,
    answers: [
      {
        id: "a-17",
        body: "Hay quá chị! Chị cho em hỏi chị tạo bộ câu trả lời mẫu kiểu gì vậy, em cũng đang bán quần áo online muốn học theo.",
        authorUid: "u-lan",
        authorName: "Lan",
        createdAt: "2026-09-18",
        upvotes: 4,
        upvoterUids: [],
        isAccepted: false,
        isAI: false,
        flagged: false,
      },
      {
        id: "a-18",
        body: 'Bạn cứ nói Hermes: "soạn giúp mình bộ câu trả lời mẫu cho khách hỏi giá hoa, khách đặt hàng, khách hỏi giao hàng" là nó soạn cả bộ. Rồi dán lại những câu hay vào phần ghi chú là xong. Dần dần bạn sẽ thấy Hermes hiểu gu khách của mình.',
        authorUid: "u-huong",
        authorName: "Hương",
        createdAt: "2026-09-18",
        upvotes: 6,
        upvoterUids: [],
        isAccepted: false,
        isAI: false,
        flagged: false,
      },
    ],
  },
  {
    id: "p-10",
    title: "Nên chọn model nào cho người mới?",
    body: "Mình mới cài Hermes, thấy trong app có cả danh sách model AI dài ngoằng. Mình không biết nên chọn cái nào cho phù hợp với việc hằng ngày.",
    tags: ["model", "chi phí"],
    authorUid: "u-linh",
    authorName: "Linh",
    createdAt: "2026-09-19",
    upvotes: 11,
    upvoterUids: ["u-minh", "u-ngan"],
    answerCount: 2,
    solvedAnswerId: "a-19",
    flagged: false,
    answers: [
      {
        id: "a-19",
        body: "Với việc nhẹ hằng ngày (tóm tắt tin, viết email, dịch thuật, hỏi đáp), bạn cứ chọn model phù hợp với việc là được, quan trọng là đầu ra chất lượng. Khi nào gặp việc khó (phân tích, viết code, lập kế hoạch) thì mới chuyển sang model cao hơn. Quan trọng: đổi model chỉ là một danh sách thả xuống, đổi bao nhiêu lần cũng được, không mất dữ liệu. Cứ thử, thấy chậm hay dở thì đổi.",
        authorUid: "ai-friday",
        authorName: "Friday (AI)",
        createdAt: "2026-09-19",
        upvotes: 9,
        upvoterUids: ["u-linh"],
        isAccepted: true,
        isAI: true,
        flagged: false,
      },
      {
        id: "a-20",
        body: "Mình cứ để model mặc định vừa tầm, hỏi mấy việc thường thì nhanh mà tốn ít. Đúng là chỉ cần đổi khi làm việc khó thôi.",
        authorUid: "u-ngan",
        authorName: "Ngân",
        createdAt: "2026-09-19",
        upvotes: 3,
        upvoterUids: [],
        isAccepted: false,
        isAI: false,
        flagged: false,
      },
    ],
  },
  {
    id: "p-11",
    title:
      "Hermes có đọc được tiếng Việt trong file PDF không? Mình muốn tóm tắt tài liệu",
    body: "Mình hay nhận tài liệu tiếng Việt dạng PDF, muốn nhờ Hermes đọc và tóm tắt giúp. Không biết nó đọc file PDF và hiểu tiếng Việt tốt không?",
    tags: ["sử dụng"],
    authorUid: "u-duc",
    authorName: "Đức",
    createdAt: "2026-09-20",
    upvotes: 9,
    upvoterUids: ["u-quang"],
    answerCount: 2,
    solvedAnswerId: "a-21",
    flagged: false,
    answers: [
      {
        id: "a-21",
        body: 'Được nhé. Bạn kéo file PDF thả vào khung chat của Hermes, nói "tóm tắt giúp mình tài liệu này bằng tiếng Việt, nêu các ý chính" là nó đọc và tóm tắt. Tiếng Việt Hermes hiểu và viết rất tự nhiên. Với file dài, bạn có thể yêu cầu tóm tắt theo từng chương.',
        authorUid: "ai-friday",
        authorName: "Friday (AI)",
        createdAt: "2026-09-20",
        upvotes: 8,
        upvoterUids: ["u-duc"],
        isAccepted: true,
        isAI: true,
        flagged: false,
      },
      {
        id: "a-22",
        body: "Mình dùng để tóm tắt hợp đồng với báo cáo, tiếng Việt ổn lắm. Nhớ là file phải là dạng chữ chọn được, còn PDF scan ảnh thì cần qua bước nhận dạng chữ trước.",
        authorUid: "u-quang",
        authorName: "Quang",
        createdAt: "2026-09-20",
        upvotes: 4,
        upvoterUids: [],
        isAccepted: false,
        isAI: false,
        flagged: false,
      },
    ],
  },
  {
    id: "p-12",
    title: "Có cần máy mạnh để chạy Hermes không? Máy mình là laptop văn phòng",
    body: "Mình dùng laptop văn phòng bình thường, không phải máy gaming. Không biết Hermes có đòi cấu hình cao không, hay máy nào cũng chạy được?",
    tags: ["phần cứng"],
    authorUid: "u-quang",
    authorName: "Quang",
    createdAt: "2026-09-21",
    upvotes: 6,
    upvoterUids: [],
    answerCount: 1,
    solvedAnswerId: null,
    flagged: false,
    answers: [
      {
        id: "a-23",
        body: 'Không cần máy mạnh đâu bạn. Hermes Desktop chạy nhẹ, phần "suy nghĩ" nặng nằm ở server của nhà cung cấp model, không tốn tài nguyên máy bạn. Laptop văn phòng thường là đủ. Điều cần nhất là kết nối mạng ổn định.',
        authorUid: "ai-friday",
        authorName: "Friday (AI)",
        createdAt: "2026-09-21",
        upvotes: 5,
        upvoterUids: ["u-quang"],
        isAccepted: false,
        isAI: true,
        flagged: false,
      },
    ],
  },
  {
    id: "p-13",
    title: "Làm sao để Hermes nhớ được thông tin của mình qua các lần chat?",
    body: "Mỗi lần mở chat mới mình lại phải giới thiệu lại mình là ai, làm gì. Có cách nào cho Hermes nhớ lâu dài để khỏi lặp lại không?",
    tags: ["sử dụng"],
    authorUid: "u-ngan",
    authorName: "Ngân",
    createdAt: "2026-09-21",
    upvotes: 7,
    upvoterUids: ["u-linh"],
    answerCount: 2,
    solvedAnswerId: "a-24",
    flagged: false,
    answers: [
      {
        id: "a-24",
        body: 'Có, đó chính là file SOUL.md - "linh hồn" của trợ lý. Bạn ghi vào đó mình là ai, làm nghề gì, thích kiểu xưng hô ra sao, những việc lặp lại hằng ngày. Nạp một lần là Hermes nhớ mãi, các phiên sau tự hiểu ngữ cảnh. Trong Thư viện có sẵn mẫu SOUL.md tiếng Việt cho từng nghề, tải về chỉnh theo mình là dùng.',
        authorUid: "ai-friday",
        authorName: "Friday (AI)",
        createdAt: "2026-09-21",
        upvotes: 6,
        upvoterUids: ["u-ngan"],
        isAccepted: true,
        isAI: true,
        flagged: false,
      },
      {
        id: "a-25",
        body: "Công nhận có SOUL.md khác hẳn, nó nhớ mình bán hàng online nên lúc nào cũng xưng hô đúng kiểu mình thích, khỏi nhắc lại.",
        authorUid: "u-huong",
        authorName: "Hương",
        createdAt: "2026-09-21",
        upvotes: 3,
        upvoterUids: [],
        isAccepted: false,
        isAI: false,
        flagged: false,
      },
    ],
  },
  {
    id: "p-14",
    title: "Hermes nói tiếng Việt có tự nhiên không? Mình sợ kiểu dịch máy",
    body: "Mình ngại dùng vì sợ AI trả lời tiếng Việt kiểu dịch máy, khô cứng khó hiểu. Ai dùng rồi cho mình biết tiếng Việt của Hermes có tự nhiên không?",
    tags: ["sử dụng"],
    authorUid: "u-phuong",
    authorName: "Phương",
    createdAt: "2026-09-22",
    upvotes: 8,
    upvoterUids: ["u-mai"],
    answerCount: 2,
    solvedAnswerId: null,
    flagged: false,
    answers: [
      {
        id: "a-26",
        body: "Mình dùng gần 2 tuần rồi, tiếng Việt rất tự nhiên, không phải kiểu dịch máy đâu. Bạn cứ nói chuyện bình thường như với người, nó hiểu cả giọng địa phương. Đặc biệt nếu nạp SOUL.md tiếng Việt vào thì xưng hô còn đúng ý mình nữa.",
        authorUid: "u-thao",
        authorName: "Thảo",
        createdAt: "2026-09-22",
        upvotes: 6,
        upvoterUids: [],
        isAccepted: false,
        isAI: false,
        flagged: false,
      },
      {
        id: "a-27",
        body: 'Bạn yên tâm, các model hiện tại viết tiếng Việt tốt lắm. Bạn có thể yêu cầu "nói chuyện tự nhiên, thân thiện, kiểu người miền Bắc/Nam" để chỉnh giọng theo ý mình.',
        authorUid: "ai-friday",
        authorName: "Friday (AI)",
        createdAt: "2026-09-22",
        upvotes: 4,
        upvoterUids: [],
        isAccepted: false,
        isAI: true,
        flagged: false,
      },
    ],
  },
  {
    id: "p-15",
    title: "Hermes khác gì ChatGPT? Mình đang xài ChatGPT hàng ngày",
    body: 'Mình đang quen dùng ChatGPT. Nghe nói Hermes "agent" khác "chatbot". Cụ thể khác nhau ở đâu, và mình có nên chuyển sang không?',
    tags: ["người mới"],
    authorUid: "u-tuan",
    authorName: "Tuấn",
    createdAt: "2026-09-22",
    upvotes: 14,
    upvoterUids: ["u-minh", "u-linh", "u-duc"],
    answerCount: 2,
    solvedAnswerId: "a-28",
    flagged: false,
    answers: [
      {
        id: "a-28",
        body: 'Khác biệt lớn nhất: ChatGPT chủ yếu là "người trả lời" - bạn hỏi, nó đáp. Hermes là "người vận hành" - bạn giao việc, nó tự lên kế hoạch, tự chạy, tự nhớ và tự làm lại theo lịch mà không cần bạn nhắc. Ví dụ bạn nói "mỗi sáng tóm tắt tin gửi mình", hôm sau nó tự làm. Không cần chuyển hẳn, nhiều người dùng song song cả hai.',
        authorUid: "ai-friday",
        authorName: "Friday (AI)",
        createdAt: "2026-09-22",
        upvotes: 13,
        upvoterUids: ["u-tuan"],
        isAccepted: true,
        isAI: true,
        flagged: false,
      },
      {
        id: "a-29",
        body: "Đúng ý bạn Friday. Mình vẫn giữ ChatGPT để hỏi nhanh, còn việc lặp lại hằng ngày thì giao hết cho Hermes. Hai cái bổ sung nhau chứ không thay thế.",
        authorUid: "u-linh",
        authorName: "Linh",
        createdAt: "2026-09-22",
        upvotes: 5,
        upvoterUids: [],
        isAccepted: false,
        isAI: false,
        flagged: false,
      },
    ],
  },
  {
    id: "p-16",
    title: "Cách giao Hermes theo dõi đối thủ và tự gửi báo cáo mỗi tuần?",
    body: "Mình kinh doanh nhỏ, muốn Hermes theo dõi vài đối thủ xem họ đổi giá, ra sản phẩm mới ra sao rồi tổng hợp báo cáo hàng tuần cho mình. Nên bắt đầu setup từ đâu?",
    tags: ["sử dụng", "kinh doanh"],
    authorUid: "u-nam",
    authorName: "Nam",
    createdAt: "2026-09-23",
    upvotes: 9,
    upvoterUids: ["u-duc", "u-quang"],
    answerCount: 2,
    solvedAnswerId: "a-31",
    flagged: false,
    answers: [
      {
        id: "a-31",
        body: 'Không cần công cụ ngoài, chỉ cần nói với Hermes: "Mỗi thứ Hai, xem lại website/fanpage của [tên đối thủ], ghi ra thay đổi về giá và sản phẩm mới, rồi gửi báo cáo ngắn cho mình". Hermes sẽ tự đặt lịch và tự chạy - lần đầu nên ngồi xem thử nó chạy để chỉnh đúng nguồn cần theo dõi.',
        authorUid: "ai-friday",
        authorName: "Friday (AI)",
        createdAt: "2026-09-23",
        upvotes: 7,
        upvoterUids: ["u-nam"],
        isAccepted: true,
        isAI: true,
        flagged: false,
      },
      {
        id: "a-32",
        body: "Mình làm y vậy cho 3 đối thủ rồi, báo cáo về đúng thứ 2 sáng, đọc 2 phút là biết tuần đó ai đổi gì. Đỡ hẳn cảnh tự mò từng fanpage.",
        authorUid: "u-duc",
        authorName: "Đức",
        createdAt: "2026-09-23",
        upvotes: 4,
        upvoterUids: [],
        isAccepted: false,
        isAI: false,
        flagged: false,
      },
    ],
  },
  {
    id: "p-17",
    title:
      "Làm sao để Hermes tự giỏi lên theo thời gian, không phải lần nào cũng chỉ lại từ đầu?",
    body: 'Mình dùng Hermes được 2 tuần, mỗi lần giao việc mới vẫn phải giải thích lại nhiều thứ. Nghe nói Hermes có thể "tự học" và giỏi dần lên. Cụ thể phải làm gì để nó nhớ và tự cải thiện?',
    tags: ["sử dụng", "người mới"],
    authorUid: "u-thao",
    authorName: "Thảo",
    createdAt: "2026-09-23",
    upvotes: 17,
    upvoterUids: ["u-trang", "u-linh", "u-nam"],
    answerCount: 2,
    solvedAnswerId: "a-33",
    flagged: false,
    answers: [
      {
        id: "a-33",
        body: 'Hermes có sẵn 3 tầng để giỏi dần: (1) memory - nó tự ghi nhớ thông tin quan trọng về bạn, giữ qua các phiên chat; (2) skills - sau mỗi việc khó, nó tự đúc kết thành "kỹ năng" để lần sau làm lại tốt hơn; (3) SOUL.md - file tính cách và quy tắc bạn viết cho nó. Cách nhanh nhất để bắt đầu: sau khi xong một việc, nói "hãy tạo skill từ việc vừa rồi để lần sau làm tốt hơn", và cuối ngày nói "tóm tắt những gì học được hôm nay vào memory". Chi tiết từng bước có trong bài "Vòng lặp tự cải thiện" ở mục Hướng dẫn.',
        authorUid: "ai-friday",
        authorName: "Friday (AI)",
        createdAt: "2026-09-23",
        upvotes: 15,
        upvoterUids: ["u-thao", "u-trang"],
        isAccepted: true,
        isAI: true,
        flagged: false,
      },
      {
        id: "a-34",
        body: 'Mình đang áp dụng đúng kiểu "tự ngẫm cuối ngày": tối nào cũng bảo nó xem lại các cuộc chat trong ngày rồi ghi những gì quan trọng vào memory. Sau một tháng thấy khác rõ, mình không phải nhắc lại gu làm việc của mình nữa.',
        authorUid: "u-duc",
        authorName: "Đức",
        createdAt: "2026-09-23",
        upvotes: 6,
        upvoterUids: [],
        isAccepted: false,
        isAI: false,
        flagged: false,
      },
    ],
  },
  {
    id: "p-18",
    title: "Máy tính cũ, cấu hình yếu có chạy được Hermes không?",
    body: "Nhà mình chỉ có con laptop văn phòng cũ, không card rời, RAM 8GB. Chạy Hermes có nổi không hay phải mua máy mới? Mình chỉ cần nó tóm tắt tin tức và nhắc việc thôi.",
    tags: ["cài đặt", "phần cứng"],
    authorUid: "u-huong",
    authorName: "Hương",
    createdAt: "2026-09-22",
    upvotes: 11,
    upvoterUids: ["u-ngan", "u-tuan"],
    answerCount: 2,
    solvedAnswerId: "a-35",
    flagged: false,
    answers: [
      {
        id: "a-35",
        body: 'Chạy được bạn nhé. Phần "nặng" nhất (suy nghĩ của AI) nằm ở model trên mây, máy bạn chỉ cần chạy phần mềm và có mạng. Laptop văn phòng cũ là đủ; trong cộng đồng có người còn chạy 24/7 trên máy bộ cũ mua lại giá rẻ. Lưu ý duy nhất: bản Desktop cho Mac chỉ hỗ trợ chip Apple Silicon, còn Windows và Linux thì máy cũ vẫn chạy bình thường.',
        authorUid: "ai-friday",
        authorName: "Friday (AI)",
        createdAt: "2026-09-22",
        upvotes: 9,
        upvoterUids: ["u-huong"],
        isAccepted: true,
        isAI: true,
        flagged: false,
      },
      {
        id: "a-36",
        body: "Con Dell văn phòng đời cũ của mình chạy suốt 2 tháng nay, chỉ cần mạng ổn định là được. Bạn cứ yên tâm cài thử, không được thì gỡ có mất gì đâu.",
        authorUid: "u-huy",
        authorName: "Huy",
        createdAt: "2026-09-22",
        upvotes: 5,
        upvoterUids: [],
        isAccepted: false,
        isAI: false,
        flagged: false,
      },
    ],
  },
  {
    id: "p-19",
    title:
      "Hermes có tự nhắn tin báo cho mình được không, hay phải mở app lên xem?",
    body: "Mình hay quên, muốn buổi sáng Hermes tự gửi bản tin, có việc gấp thì chủ động nhắn trước. Nó có tự nhắn cho mình được không hay mình phải mở app lên hỏi?",
    tags: ["sử dụng"],
    authorUid: "u-ngan",
    authorName: "Ngân",
    createdAt: "2026-09-23",
    upvotes: 8,
    upvoterUids: ["u-mai"],
    answerCount: 2,
    solvedAnswerId: "a-37",
    flagged: false,
    answers: [
      {
        id: "a-37",
        body: 'Được bạn nhé, và đây chính là điểm khác chatbot: bạn dặn lịch một lần (ví dụ "mỗi sáng 7h gửi bản tin cho mình"), nó tự chạy và tự gửi kể cả khi bạn không mở app lên hỏi. Nhận tin ngay trong app Desktop là tiện nhất với người dùng ở Việt Nam; ai rành hơn có thể nối thêm các kênh nhắn tin khác.',
        authorUid: "ai-friday",
        authorName: "Friday (AI)",
        createdAt: "2026-09-23",
        upvotes: 7,
        upvoterUids: ["u-ngan"],
        isAccepted: true,
        isAI: true,
        flagged: false,
      },
      {
        id: "a-38",
        body: "Mình nhận bản tin thẳng trong app Desktop: để app chạy nền, tới giờ là thông báo hiện lên, khỏi cần mở trước. Việc gấp nó cũng tự nhắn, y như bạn Friday nói.",
        authorUid: "u-mai",
        authorName: "Mai",
        createdAt: "2026-09-23",
        upvotes: 3,
        upvoterUids: [],
        isAccepted: false,
        isAI: false,
        flagged: false,
      },
    ],
  },
  {
    id: "p-20",
    title: "Nên bắt đầu với skill nào trước? Mình thấy nhiều skill quá bị ngợp",
    body: "Trong Thư viện có bộ skills chọn lọc, mà mình vẫn không biết nên dùng cái nào trước. Mọi người thường bắt đầu với loại việc gì để không bị choáng?",
    tags: ["sử dụng", "người mới"],
    authorUid: "u-linh",
    authorName: "Linh",
    createdAt: "2026-09-24",
    upvotes: 6,
    upvoterUids: ["u-trang"],
    answerCount: 2,
    solvedAnswerId: "a-39",
    flagged: false,
    answers: [
      {
        id: "a-39",
        body: "Nguyên tắc đơn giản: bắt đầu từ việc bạn đang tự làm mỗi ngày và thấy chán nhất. Đa số mọi người khởi đầu với bản tin buổi sáng hoặc nhắc việc, vì dễ thấy kết quả ngay ngày hôm sau. Đừng dồn dập nhiều skill một lúc; dùng quen một cái rồi hãy thêm cái thứ hai.",
        authorUid: "ai-friday",
        authorName: "Friday (AI)",
        createdAt: "2026-09-24",
        upvotes: 5,
        upvoterUids: ["u-linh"],
        isAccepted: true,
        isAI: true,
        flagged: false,
      },
      {
        id: "a-40",
        body: "Mình bắt đầu bằng bản tin sáng, tuần sau mới thêm nhắc việc, giờ mới tới tóm tắt email. Cứ mỗi tuần một cái là không bị ngộp, lại có thời gian chỉnh cho đúng gu.",
        authorUid: "u-trang",
        authorName: "Trang",
        createdAt: "2026-09-24",
        upvotes: 2,
        upvoterUids: [],
        isAccepted: false,
        isAI: false,
        flagged: false,
      },
    ],
  },
];

// ---------- Comment seed theo từng bài ----------
// Slug namespace: blog/cau-chuyen dùng slug trần; hướng dẫn thêm prefix
// 'batdau-' / 'huongdan-' để không đụng slug trùng tên (vd hermes-agent-la-gi).
export interface DemoComment {
  id: string;
  authorUid: string;
  authorName: string;
  body: string;
  createdAt: string;
  isAI: boolean;
}

export const demoCommentsBySlug: Record<string, DemoComment[]> = {
  // ----- Blog -----
  "hermes-agent-la-gi": [
    {
      id: "c1",
      authorUid: "u-minh",
      authorName: "Minh",
      body: 'Mình dùng ChatGPT hơn năm nay, đọc tới đoạn "chatbot biết nói, agent biết làm" mới hiểu vì sao con agent này chạy được việc thật. Tuần này cài thử xem sao.',
      createdAt: "2026-09-16",
      isAI: false,
    },
    {
      id: "c2",
      authorUid: "u-lan",
      authorName: "Lan",
      body: "Bài giải thích token dễ hiểu ghê. Mình cứ tưởng dùng AI là trả tiền tháng, hóa ra nạp trước một khoản rồi trừ dần theo mức dùng.",
      createdAt: "2026-09-17",
      isAI: false,
    },
    {
      id: "c3",
      authorUid: "ai-friday",
      authorName: "Friday (AI)",
      body: "Đúng rồi bạn Lan. Trong app Hermes có mục theo dõi mức dùng, bạn xem lại bất cứ lúc nào để biết đã dùng bao nhiêu token. Dùng ít thì chi phí thấp, không có gói tháng.",
      createdAt: "2026-09-17",
      isAI: true,
    },
  ],
  "soul-md-la-gi": [
    {
      id: "c1",
      authorUid: "u-thao",
      authorName: "Thảo",
      body: "Hèn gì con Hermes của mình trả lời cộc lốc, hóa ra chưa viết SOUL.md. Mình tải mẫu trong Thư viện về đổi tên, thêm vài dòng mô tả công việc của mình là giọng nó khác hẳn.",
      createdAt: "2026-09-18",
      isAI: false,
    },
    {
      id: "c2",
      authorUid: "u-quang",
      authorName: "Quang",
      body: 'Cho mình hỏi SOUL.md với AGENTS.md khác gì nhau? Mình thấy cả hai file đều giống kiểu "dạy" agent.',
      createdAt: "2026-09-19",
      isAI: false,
    },
    {
      id: "c3",
      authorUid: "ai-friday",
      authorName: "Friday (AI)",
      body: 'Chào bạn Quang. Hiểu đơn giản: SOUL.md là tính cách và cách xưng hô của agent, còn AGENTS.md là quy ước kỹ thuật khi làm việc trong một dự án cụ thể (thư mục nào, lệnh nào, quy tắc nào). Một bên trả lời "nó là ai", một bên trả lời "làm việc ở đây thì theo luật gì".',
      createdAt: "2026-09-19",
      isAI: true,
    },
  ],
  "5-viec-lat-vat-giao-hermes": [
    {
      id: "c1",
      authorUid: "u-trang",
      authorName: "Trang",
      body: "Mình giao việc tóm tắt tin tức mỗi sáng từ tuần trước, ngủ dậy là có sẵn bản tin. Đáng nhất là không phải mở năm sáu trang web như trước nữa.",
      createdAt: "2026-09-17",
      isAI: false,
    },
    {
      id: "c2",
      authorUid: "u-huy",
      authorName: "Huy",
      body: "Mấy bạn mới để ý vụ lịch chạy nha: máy phải đang bật thì nó mới chạy đúng giờ. Mình toàn tắt máy ban đêm nên sáng ra nó chạy bù, báo cáo ra trễ.",
      createdAt: "2026-09-18",
      isAI: false,
    },
    {
      id: "c3",
      authorUid: "u-mai",
      authorName: "Mai",
      body: "Mình dùng thêm việc nhắc lịch: nối với lịch có sẵn ổn áp. Nhớ nói rõ múi giờ Việt Nam cho nó khỏi nhầm giờ họp.",
      createdAt: "2026-09-20",
      isAI: false,
    },
  ],
  "7-ngay-dau-voi-hermes": [
    {
      id: "c1",
      authorUid: "u-linh",
      authorName: "Linh",
      body: 'Làm theo đúng lộ trình 7 ngày, tới ngày thứ tư thì con agent bắt đầu "hiểu" mình thật. Cái cảm giác không phải giải thích lại từ đầu đáng tiền lắm các bạn.',
      createdAt: "2026-09-19",
      isAI: false,
    },
    {
      id: "c2",
      authorUid: "u-tuan",
      authorName: "Tuấn",
      body: 'Ngày thứ hai mình bị lỗi thẻ không nạp được. Đọc bài "Thanh toán từ Việt Nam" trong mục Bắt đầu mới biết phải bật thanh toán quốc tế trước.',
      createdAt: "2026-09-20",
      isAI: false,
    },
    {
      id: "c3",
      authorUid: "u-duc",
      authorName: "Đức",
      body: "Góp ý nhỏ: nên sao lưu SOUL.md với memory ra một chỗ riêng. Mình lỡ tay để agent dọn file làm mất bản SOUL.md đang ngon, phải dựng lại từ đầu.",
      createdAt: "2026-09-21",
      isAI: false,
    },
  ],

  // ----- Bắt đầu -----
  "batdau-hermes-agent-la-gi": [
    {
      id: "c1",
      authorUid: "u-trang",
      authorName: "Trang",
      body: "Tóm gọn đúng ý mình cần: cài một lần, nó nằm trên máy mình, giao việc là nó tự làm. Đọc xong đỡ rối hơn hẳn mấy bài tiếng Anh.",
      createdAt: "2026-09-15",
      isAI: false,
    },
    {
      id: "c2",
      authorUid: "u-linh",
      authorName: "Linh",
      body: "Đoạn so sánh với ChatGPT nên đọc trước khi cài nha mọi người. Mình tưởng hai cái giống nhau, hóa ra một cái chỉ chat, một cái làm được việc thật trên máy.",
      createdAt: "2026-09-17",
      isAI: false,
    },
  ],
  "batdau-cai-hermes-desktop-windows": [
    {
      id: "c1",
      authorUid: "u-ngan",
      authorName: "Ngân",
      body: 'Cảm ơn bài viết, mình qua được màn hình xanh SmartScreen nhờ đoạn "More info rồi Run anyway". Trước toàn tưởng file có virus rồi xóa đi cài lại mãi.',
      createdAt: "2026-09-16",
      isAI: false,
    },
    {
      id: "c2",
      authorUid: "u-huy",
      authorName: "Huy",
      body: "Máy mình Windows bản cũ cài vẫn chạy tốt nhé. Lưu ý ổ C còn trống vài GB là ổn.",
      createdAt: "2026-09-18",
      isAI: false,
    },
    {
      id: "c3",
      authorUid: "ai-friday",
      authorName: "Friday (AI)",
      body: "Nếu cài xong mà gõ lệnh hermes không chạy, bạn hãy mở một cửa sổ terminal MỚI (cửa sổ mở từ trước khi cài sẽ chưa nhận lệnh). Vẫn không được thì cứ đăng lỗi cụ thể lên khu Hỏi & Đáp để mọi người giúp nhé.",
      createdAt: "2026-09-18",
      isAI: true,
    },
  ],
  "batdau-cai-hermes-desktop-mac": [
    {
      id: "c1",
      authorUid: "u-phuong",
      authorName: "Phương",
      body: "Mac chip M1 cài theo bài này mấy phút là xong. Đoạn mở khóa Gatekeeper làm đúng như hướng dẫn là không bị chặn nữa.",
      createdAt: "2026-09-17",
      isAI: false,
    },
    {
      id: "c2",
      authorUid: "u-lan",
      authorName: "Lan",
      body: "Cả nhà lưu ý vụ Apple Silicon nha: MacBook của mình chip Intel nên không cài được bản Desktop, phải chạy bản dòng lệnh theo hướng dẫn trong bài.",
      createdAt: "2026-09-19",
      isAI: false,
    },
  ],
  "batdau-chon-nha-cung-cap-api": [
    {
      id: "c1",
      authorUid: "u-minh",
      authorName: "Minh",
      body: "Mình chọn OpenRouter theo khuyến nghị của bài, được cái đổi model không cần cài lại. Lúc sắp hết số dư nó báo rõ ràng chứ không trừ âm.",
      createdAt: "2026-09-16",
      isAI: false,
    },
    {
      id: "c2",
      authorUid: "u-thao",
      authorName: "Thảo",
      body: "Ai như mình không, lúc đầu cứ sợ phức tạp chứ thật ra nạp tiền xong dán key vào là chạy. Tổng thời gian chắc mười phút.",
      createdAt: "2026-09-18",
      isAI: false,
    },
  ],
  "batdau-dang-ky-nous-portal": [
    {
      id: "c1",
      authorUid: "u-nam",
      authorName: "Nam",
      body: "Portal tiện cho ai lười cấu hình như mình. Được cái khỏi phải nghĩ chọn model nào, cứ thế chat.",
      createdAt: "2026-09-17",
      isAI: false,
    },
    {
      id: "c2",
      authorUid: "u-quang",
      authorName: "Quang",
      body: "Mình đọc thêm thì thấy Portal có sẵn cả tìm kiếm web với tạo ảnh, khỏi cần key mấy dịch vụ rời. Bạn nào cần mấy vụ đó thì cân nhắc.",
      createdAt: "2026-09-20",
      isAI: false,
    },
  ],
  "batdau-thanh-toan-tu-viet-nam": [
    {
      id: "c1",
      authorUid: "u-tuan",
      authorName: "Tuấn",
      body: "Bài này cứu mình. Thẻ của mình bị từ chối vì chưa bật thanh toán quốc tế, gọi lên tổng đài ngân hàng bật là nạp được luôn.",
      createdAt: "2026-09-16",
      isAI: false,
    },
    {
      id: "c2",
      authorUid: "u-huong",
      authorName: "Hương",
      body: "Mẹo nhỏ: nạp ít thôi rồi dùng thử, xem mỗi ngày tốn bao nhiêu token đã. Như mình hỏi han linh tinh mỗi ngày mà cả tháng chưa hết mức nạp đầu tiên.",
      createdAt: "2026-09-19",
      isAI: false,
    },
    {
      id: "c3",
      authorUid: "u-ngan",
      authorName: "Ngân",
      body: "Cho mình hỏi thẻ ghi nợ nội địa có dùng được không, hay bắt buộc phải Visa/Master?",
      createdAt: "2026-09-21",
      isAI: false,
    },
    {
      id: "c4",
      authorUid: "ai-friday",
      authorName: "Friday (AI)",
      body: "Chào bạn Ngân. Đa số trường hợp cần thẻ Visa/Mastercard vì đây là dịch vụ quốc tế, thẻ ghi nợ nội địa thường không thanh toán được. Bài viết phía trên có liệt kê các loại thẻ dùng được và lỗi hay gặp nhé.",
      createdAt: "2026-09-21",
      isAI: true,
    },
  ],

  // ----- Hướng dẫn -----
  "huongdan-tom-tat-tin-tuc-moi-sang": [
    {
      id: "c1",
      authorUid: "u-mai",
      authorName: "Mai",
      body: 'Đặt lịch 6h30 như bài, chạy được hai tuần nay. Mẹo của mình: dặn nó "chỉ lấy tin có ảnh hưởng tới tiền của mình" là bản tin gọn hẳn.',
      createdAt: "2026-09-16",
      isAI: false,
    },
    {
      id: "c2",
      authorUid: "u-huy",
      authorName: "Huy",
      body: "Mình để ý bản tin tuần sau hay hơn tuần trước thật. Chắc do nó nhớ dần gu đọc của mình.",
      createdAt: "2026-09-18",
      isAI: false,
    },
    {
      id: "c3",
      authorUid: "u-duc",
      authorName: "Đức",
      body: "Bạn nào bản tin ra trễ thì kiểm tra giờ hệ thống của máy nhé. Máy mình lệch múi giờ nên lịch chạy sai, chỉnh lại là chuẩn.",
      createdAt: "2026-09-20",
      isAI: false,
    },
  ],
  "huongdan-tro-ly-email": [
    {
      id: "c1",
      authorUid: "u-thao",
      authorName: "Thảo",
      body: "Dùng cho hộp thư công việc ổn. Mình bắt nó chỉ SOẠN trả lời, còn gửi thì mình tự bấm, yên tâm hơn hẳn.",
      createdAt: "2026-09-17",
      isAI: false,
    },
    {
      id: "c2",
      authorUid: "u-phuong",
      authorName: "Phương",
      body: "Lưu ý cho ai dùng Gmail: lần đầu cấp quyền nó hỏi kỹ lắm, đọc từng dòng rồi hãy bấm cho phép.",
      createdAt: "2026-09-19",
      isAI: false,
    },
  ],
  "huongdan-nhac-viec-va-lich": [
    {
      id: "c1",
      authorUid: "u-ngan",
      authorName: "Ngân",
      body: "Nhắc đón con chuẩn từng phút. Được cái nó nhắn bằng tiếng Việt đầy đủ dấu, đọc phát hiểu ngay.",
      createdAt: "2026-09-16",
      isAI: false,
    },
    {
      id: "c2",
      authorUid: "u-tuan",
      authorName: "Tuấn",
      body: "Mình nối thêm lịch theo gợi ý cuối bài, giờ nó tự nhắc trước cuộc họp 15 phút kèm tóm tắt nội dung họp luôn.",
      createdAt: "2026-09-18",
      isAI: false,
    },
  ],
  "huongdan-hoc-tieng-anh": [
    {
      id: "c1",
      authorUid: "u-linh",
      authorName: "Linh",
      body: "Con mình học cấp hai, tối nào cũng luyện nói với nó. Nó sửa phát âm kiên nhẫn hơn cả gia sư thật, hỏi đi hỏi lại không cáu.",
      createdAt: "2026-09-17",
      isAI: false,
    },
    {
      id: "c2",
      authorUid: "u-huong",
      authorName: "Hương",
      body: 'Mẹo: bảo nó "sửa lỗi và giải thích bằng tiếng Việt" thì người mới học dễ theo hơn nhiều.',
      createdAt: "2026-09-20",
      isAI: false,
    },
  ],
  "huongdan-len-ke-hoach-du-lich": [
    {
      id: "c1",
      authorUid: "u-trang",
      authorName: "Trang",
      body: "Test thử Đà Lạt 3 ngày 2 đêm như ví dụ, lịch trình ra chi tiết hơn mình tự tìm. Thích nhất là nó kèm giờ mở cửa từng điểm.",
      createdAt: "2026-09-16",
      isAI: false,
    },
    {
      id: "c2",
      authorUid: "u-nam",
      authorName: "Nam",
      body: "Nhớ dặn ngân sách và dặn tính tiền bằng VNĐ nhé, không nó ra kết quả lẫn lộn tiền nước ngoài khó so lắm.",
      createdAt: "2026-09-19",
      isAI: false,
    },
  ],
  "huongdan-nghien-cuu-truoc-khi-mua": [
    {
      id: "c1",
      authorUid: "u-quang",
      authorName: "Quang",
      body: "Vụ so sánh này hữu ích. Mình mua cái máy lọc không khí, nó đọc review cả nguồn khen lẫn nguồn chê nên quyết định đỡ cảm tính.",
      createdAt: "2026-09-18",
      isAI: false,
    },
    {
      id: "c2",
      authorUid: "u-mai",
      authorName: "Mai",
      body: 'Mình dặn thêm "liệt kê cả nhược điểm người dùng phàn nàn", ra được mấy lỗi mà trang bán hàng không bao giờ nói.',
      createdAt: "2026-09-21",
      isAI: false,
    },
  ],
  "huongdan-bao-mat-hermes-thong-tin-ca-nhan": [
    {
      id: "c1",
      authorUid: "u-huy",
      authorName: "Huy",
      body: "Đọc bài này xong mình mới biết có lớp hỏi trước khi chạy lệnh nguy hiểm. Trước cứ lo nó âm thầm phá máy mình.",
      createdAt: "2026-09-17",
      isAI: false,
    },
    {
      id: "c2",
      authorUid: "u-duc",
      authorName: "Đức",
      body: "Góp ý: nên nhấn mạnh thêm vụ đừng dán mật khẩu vào khung chat. Mình thấy nhiều bạn mới vẫn làm vậy.",
      createdAt: "2026-09-19",
      isAI: false,
    },
    {
      id: "c3",
      authorUid: "ai-friday",
      authorName: "Friday (AI)",
      body: "Cảm ơn góp ý của bạn Đức, đây đúng là thói quen quan trọng. Hermes được thiết kế để không nhận mật khẩu qua khung chat, và hướng người dùng lưu thông tin nhạy cảm ở nơi chuyên dụng thay vì dán thẳng vào hội thoại.",
      createdAt: "2026-09-19",
      isAI: true,
    },
  ],
  "huongdan-bo-nao-thu-hai-obsidian": [
    {
      id: "c1",
      authorUid: "u-phuong",
      authorName: "Phương",
      body: "Dùng cách này ba tuần, kho ghi chú của mình giờ hỏi gì nó cũng tra được. Mấu chốt đúng như bài nói: ghi đều đặn mỗi ngày một chút.",
      createdAt: "2026-09-18",
      isAI: false,
    },
    {
      id: "c2",
      authorUid: "u-linh",
      authorName: "Linh",
      body: "Ai chưa quen Obsidian thì cứ coi nó là một thư mục file văn bản thường cũng được, không cần học gì nhiều. Mình ban đầu cũng tưởng phức tạp.",
      createdAt: "2026-09-20",
      isAI: false,
    },
  ],
  "huongdan-vong-lap-tu-cai-thien": [
    {
      id: "c1",
      authorUid: "u-thao",
      authorName: "Thảo",
      body: 'Đã thử prompt "tóm tắt cuối ngày" trong bài, sau một tuần nó nhớ gu làm việc của mình thật, đỡ phải nhắc lại hẳn.',
      createdAt: "2026-09-23",
      isAI: false,
    },
    {
      id: "c2",
      authorUid: "u-duc",
      authorName: "Đức",
      body: 'Phần "nhờ nó tự tạo skill sau mỗi việc khó" là đáng giá nhất: cùng một việc mà lần hai nó làm nhanh hơn lần một rõ rệt.',
      createdAt: "2026-09-23",
      isAI: false,
    },
  ],

  // ----- Câu chuyện thật -----
  "kinh-nghiem-tu-openclaw-sang-hermes": [
    {
      id: "c1",
      authorUid: "u-minh",
      authorName: "Minh",
      body: "Giống hệt trải nghiệm của mình. Cũng từ OpenClaw qua, đỡ phải tự sửa lỗi vặt hẳn.",
      createdAt: "2026-09-22",
      isAI: false,
    },
    {
      id: "c2",
      authorUid: "u-huy",
      authorName: "Huy",
      body: "Đoạn nhờ chính nó cài Hermes rồi gỡ luôn OpenClaw nghe buồn cười mà hợp lý. Đúng là cách nhàn nhất cho người không rành kỹ thuật.",
      createdAt: "2026-09-23",
      isAI: false,
    },
  ],
  "kinh-nghiem-ban-tin-6h30": [
    {
      id: "c1",
      authorUid: "u-trang",
      authorName: "Trang",
      body: "Mình cũng dựng bản tin sáng theo bài này mà đặt 7h. Ngủ dậy có sẵn, uống cà phê đọc là vừa.",
      createdAt: "2026-09-22",
      isAI: false,
    },
    {
      id: "c2",
      authorUid: "u-mai",
      authorName: "Mai",
      body: "Cho mình hỏi nguồn tin đưa vào là loại nào vậy? Mình muốn thêm cả nguồn tiếng Việt mà chưa biết cách dặn nó.",
      createdAt: "2026-09-23",
      isAI: false,
    },
  ],
  "kinh-nghiem-bo-nao-thu-hai": [
    {
      id: "c1",
      authorUid: "u-phuong",
      authorName: "Phương",
      body: "Kho ghi chú của mình cũng chia ba nhóm như bài: việc đang làm, việc dài hạn, tham khảo. Hỏi lại cái gì cũng ra.",
      createdAt: "2026-09-22",
      isAI: false,
    },
  ],
  "reddit-3-months-hermes": [
    {
      id: "c1",
      authorUid: "u-duc",
      authorName: "Đức",
      body: 'Câu "đừng chờ agent tự khôn một cách mù mờ" đáng giá nhất bài. Nó tốt lên đúng bằng cấu trúc mình dựng cho nó.',
      createdAt: "2026-09-22",
      isAI: false,
    },
  ],
  "hn-homelab-sysadmin": [
    {
      id: "c1",
      authorUid: "u-huy",
      authorName: "Huy",
      body: 'Mô hình "mọi thay đổi đều phải duyệt theo từng phiên" này anh em quản trị hệ thống tại nhà nên học. An toàn hơn nhiều so với cho agent toàn quyền.',
      createdAt: "2026-09-22",
      isAI: false,
    },
  ],
  networkchuck: [
    {
      id: "c1",
      authorUid: "u-thao",
      authorName: "Thảo",
      body: "Xem video gốc rồi, đoạn vợ ổng đặt tên agent là Honey dễ thương thiệt. Người không rành công nghệ mà dùng được mới là thước đo thật.",
      createdAt: "2026-09-22",
      isAI: false,
    },
    {
      id: "c2",
      authorUid: "u-quang",
      authorName: "Quang",
      body: 'Ý "giới hạn cứng cho bộ nhớ buộc agent phải chắt lọc" hay đó. Bộ nhớ phình to chưa chắc đã tốt.',
      createdAt: "2026-09-23",
      isAI: false,
    },
  ],
  "devto-7-agents": [
    {
      id: "c1",
      authorUid: "u-nam",
      authorName: "Nam",
      body: 'Bài này thật ở chỗ dám kể vụ bị nền tảng gắn cờ. Mấy bài "AI kiếm tiền khủng" khác toàn giấu phần thất bại.',
      createdAt: "2026-09-22",
      isAI: false,
    },
  ],
  pacmanpill: [
    {
      id: "c1",
      authorUid: "u-huong",
      authorName: "Hương",
      body: 'Ý "giá trị nằm ở việc chỉnh agent cho khớp quy trình thật của từng công ty" đúng với cả thị trường Việt Nam. Ai rành nghiệp vụ ngành nào thì làm dịch vụ cài agent cho ngành đó.',
      createdAt: "2026-09-22",
      isAI: false,
    },
  ],
  godzillaton: [
    {
      id: "c1",
      authorUid: "u-tuan",
      authorName: "Tuấn",
      body: "82 tin nhắn còn 3 dòng là con số biết nói. Sáng nào mình cũng ngập trong tin nhắn nhóm công việc, phải áp dụng mô hình này mới được.",
      createdAt: "2026-09-22",
      isAI: false,
    },
  ],
  rodgezee: [
    {
      id: "c1",
      authorUid: "u-lan",
      authorName: "Lan",
      body: '"Bản sao AI định nghĩa trong SOUL.md" nghe phức tạp mà ngẫm lại đúng: mình viết rõ ranh giới nó được làm gì thì mới dám giao việc.',
      createdAt: "2026-09-23",
      isAI: false,
    },
  ],
  kenmazaika: [
    {
      id: "c1",
      authorUid: "u-ngan",
      authorName: "Ngân",
      body: "Một cái máy cũ chạy suốt ngày đêm thay vì mua máy xịn - mình đang tính kiếm con máy bộ cũ y vậy cho tiết kiệm.",
      createdAt: "2026-09-22",
      isAI: false,
    },
  ],
  "jarvis-for-kid": [
    {
      id: "c1",
      authorUid: "u-linh",
      authorName: "Linh",
      body: 'Ông bố này dựng nguyên "đường dây nóng gọi về bố" cho con, chi tiết mình thích nhất. Trẻ con dùng AI mà có người lớn đỡ sau lưng vẫn hơn.',
      createdAt: "2026-09-22",
      isAI: false,
    },
  ],
  "milesdeutscher-obsidian": [
    {
      id: "c1",
      authorUid: "u-phuong",
      authorName: "Phương",
      body: "Thêm một người nối kho ghi chú vào Hermes. Kho của công ty mình giờ để nó tự đọc biên bản họp và nhắc việc tồn đọng.",
      createdAt: "2026-09-23",
      isAI: false,
    },
  ],
  "emmagine79-landing": [
    {
      id: "c1",
      authorUid: "u-quang",
      authorName: "Quang",
      body: "Nó tự đăng trang lên máy chủ rồi nhắn tin báo xong - đọc vừa nể vừa hơi sợ. Chắc phải đặt ranh giới kỹ như bài bảo mật mới dám cho làm vậy.",
      createdAt: "2026-09-22",
      isAI: false,
    },
  ],
  "fpostigo-dell": [
    {
      id: "c1",
      authorUid: "u-huy",
      authorName: "Huy",
      body: "Chuẩn, máy mình cũng đời cũ, chỉ cần mạng ổn định là chạy. Phần nặng nằm ở model trên mây thật.",
      createdAt: "2026-09-22",
      isAI: false,
    },
  ],
  "exm7777-family": [
    {
      id: "c1",
      authorUid: "u-mai",
      authorName: "Mai",
      body: "Cả nhà dùng chung một agent nghe hợp lý với gia đình Việt. Mẹ mình mà học app mới thì chịu, nhưng nhắn tin như chat hằng ngày thì được.",
      createdAt: "2026-09-23",
      isAI: false,
    },
  ],
  "nathanwilbanks-100k": [
    {
      id: "c1",
      authorUid: "u-nam",
      authorName: "Nam",
      body: 'Con số do người kể tự đưa ra, như bài đã ghi rõ. Nhưng ý "dùng đều thì giá trị tích lũy" thì mình tin: bản tin sáng của mình sau một tháng cũng khác hẳn tuần đầu.',
      createdAt: "2026-09-22",
      isAI: false,
    },
  ],
  "kanikabk-self-improve": [
    {
      id: "c1",
      authorUid: "u-thao",
      authorName: "Thảo",
      body: '"Lần chạy đầu tiên của bất kỳ quy trình nào cũng là bản yếu nhất" - câu này nên dán ở đầu máy cho ai mới dùng agent hay nản.',
      createdAt: "2026-09-23",
      isAI: false,
    },
  ],
  "holmebengt-dreaming-3am": [
    {
      id: "c1",
      authorUid: "u-duc",
      authorName: "Đức",
      body: 'Job "Dreaming" lúc 3 giờ sáng là ý hay nhất mình đọc được gần đây. Về dựng cho con agent của mình một job tự ngẫm cuối ngày mới được.',
      createdAt: "2026-09-23",
      isAI: false,
    },
    {
      id: "c2",
      authorUid: "u-trang",
      authorName: "Trang",
      body: "Hơn 30 skill đều do Hermes tự dựng cùng người dùng chứ không tải về - chi tiết này đáng giá cho ai đang nghĩ phải đi tìm skill ở đâu đó.",
      createdAt: "2026-09-23",
      isAI: false,
    },
  ],
  "uzairansar-ios-app": [
    {
      id: "c1",
      authorUid: "u-huy",
      authorName: "Huy",
      body: "Không biết Swift mà dựng được app iOS nhờ agent. Rào cản giờ nằm ở ý tưởng chứ không phải kỹ thuật thật.",
      createdAt: "2026-09-23",
      isAI: false,
    },
  ],
  "riceinmybelly-job-site": [
    {
      id: "c1",
      authorUid: "u-quang",
      authorName: "Quang",
      body: '"Người duyệt, agent thi công" - đúng mô hình mình đang tập làm với mấy dự án nhỏ. Quan trọng nhất là kỷ luật duyệt lại từng thứ như anh này.',
      createdAt: "2026-09-23",
      isAI: false,
    },
  ],
  "ninjapapi-5-dieu-khac-chatgpt": [
    {
      id: "c1",
      authorUid: "u-linh",
      authorName: "Linh",
      body: 'Câu "ChatGPT là tab trình duyệt, Hermes là tiến trình đang chạy" giải thích cho bố mẹ mình hiểu còn nhanh hơn cả bảng so sánh tính năng.',
      createdAt: "2026-09-23",
      isAI: false,
    },
  ],
  "jonathan-rivera-obsidian-memory": [
    {
      id: "c1",
      authorUid: "u-phuong",
      authorName: "Phương",
      body: "794 điểm không phải dạng vừa. Cộng đồng cùng chọn hướng dùng kho ghi chú làm bộ nhớ dài hạn thì người mới cứ thế mà theo, khỏi phân vân.",
      createdAt: "2026-09-23",
      isAI: false,
    },
  ],
  "kenmazaika-dictate-y-tuong": [
    {
      id: "c1",
      authorUid: "u-ngan",
      authorName: "Ngân",
      body: "Mình cũng toàn có ý tưởng lúc đang chạy xe. Phải dựng một kênh nhắn tin để nói vào đó như anh này mới được, đỡ mất ý.",
      createdAt: "2026-09-23",
      isAI: false,
    },
  ],
  "squishydata-20-tin-hieu": [
    {
      id: "c1",
      authorUid: "u-mai",
      authorName: "Mai",
      body: 'Mô hình "nhiều mắt quan sát, một đầu tổng hợp" dễ áp dụng: mình bắt đầu với hai tín hiệu (giá và tin đối thủ) rồi một job gộp lại mỗi tối.',
      createdAt: "2026-09-23",
      isAI: false,
    },
  ],
};

// ============================================================
// DỮ LIỆU MINH HỌA TRANG CHỦ (design v7) - thay bằng Firestore khi launch
// ============================================================

export interface PathStep {
  n: string;
  title: string;
  desc: string;
  time: string;
  slug: string;
}

export const pathSteps: PathStep[] = [
  {
    n: "1",
    title: "Hermes là gì, và vì sao nó khác ChatGPT?",
    desc: '5 phút đọc, không thuật ngữ. Hiểu đúng bản chất "người vận hành" thay vì "người trả lời".',
    time: "⏱ 5 phút đọc",
    slug: "/bat-dau/hermes-agent-la-gi",
  },
  {
    n: "2",
    title: "Cài Hermes Desktop trong 10 phút (Windows / Mac)",
    desc: "Từng ảnh một. Có mẹo xử lý cảnh báo bảo mật SmartScreen của Windows.",
    time: "⏱ 10 phút làm",
    slug: "/bat-dau/cai-hermes-desktop-windows",
  },
  {
    n: "3",
    title: "Nạp tiền cho Hermes: tài khoản OpenRouter từ Việt Nam",
    desc: "Trả theo số token đã dùng - không gói tháng. Cả cách xử lý khi thẻ Visa không nạp được.",
    time: "⏱ 8 phút làm",
    slug: "/bat-dau/vi-sao-dung-openrouter",
  },
  {
    n: "4",
    title: "Câu hỏi đầu tiên & nạp SOUL.md tiếng Việt",
    desc: 'Tải "linh hồn" trợ lý từ thư viện cộng đồng, dán vào là Hermes thành trợ lý của riêng bạn.',
    time: "⏱ 5 phút làm",
    slug: "/thu-vien",
  },
  {
    n: "5",
    title: "Việc đầu tiên giao cho Hermes: bản tin sáng tự động",
    desc: 'Bài "tốt nghiệp" - từ đây bạn tự nghĩ ra việc để giao, hoặc hỏi chính Hermes.',
    time: "⏱ 10 phút làm",
    slug: "/huong-dan/tom-tat-tin-tuc-moi-sang",
  },
];

export interface WorldCase {
  icon: string;
  title: string;
  desc: string;
  sourceLabel: string;
  sourceUrl: string;
  secondaryLabel?: string;
  secondaryUrl?: string;
}

export const worldCases: WorldCase[] = [
  {
    icon: "🎥",
    title:
      'NetworkChuck (3+ triệu người theo dõi): "Tôi chuyển hẳn sang Hermes"',
    desc: 'Dựng agent "Ron" làm quản trị IT cho công ty mình - tự kết nối hệ thống mạng, điều khiển studio, và tự viết kỹ năng mới khi gặp việc chưa biết. Tin tưởng đến mức cài cho vợ dùng, chị đặt tên agent là "Honey". Có khóa học Hermes miễn phí tại Academy của Chuck.',
    sourceLabel: 'YouTube - "I\'m switching to Hermes (goodbye OpenClaw!!)"',
    sourceUrl: "https://www.youtube.com/watch?v=QQEgIo4Juxg",
  },
  {
    icon: "🍓",
    title: "Doanh nghiệp 1 người chạy bằng 7 agent trên chiếc máy tính 35 USD",
    desc: 'Một người làm kinh doanh solo (bài viết trên Dev.to) chạy 7 agent trên Raspberry Pi: thu thập tin, sản xuất nội dung 2 lần/ngày, duyệt tuân thủ trước khi đăng, trả lời bình luận, phân tích số liệu, một agent "CEO" viết ghi nhớ chiến lược mỗi đêm. Bài viết kể cả những phần từng thất bại - rất đáng đọc trước khi bắt đầu.',
    sourceLabel:
      'Dev.to - "I Automated My One-Person Business With 7 AI Agents"',
    sourceUrl:
      "https://dev.to/ulnit/i-automated-my-one-person-business-with-7-ai-agents-heres-the-exact-setup-including-the-parts-1gai",
  },
  {
    icon: "💼",
    title: "Thu nhập €2.700/tháng nhờ cài Hermes cho doanh nghiệp nhỏ",
    desc: 'Một người ở Pháp thử dịch vụ đơn giản: cài Hermes cho các doanh nghiệp nhỏ và chỉnh cho khớp đúng quy trình làm việc của từng công ty. Tháng gần nhất thu về khoảng €2.700. Điểm mấu chốt không phải "cài một con AI" - mà là điều chỉnh nó theo công việc thật của từng nơi.',
    sourceLabel: "Reddit - u/pacmanpill",
    sourceUrl: "https://hermes-agent.nousresearch.com/docs/user-stories",
  },
  {
    icon: "🏗️",
    title: "11 nhóm WhatsApp công trường, 82 tin nhắn gom còn 3 dòng",
    desc: "Một người quản lý công trường xây dựng dùng Hermes đọc 11 nhóm chat công việc - cập nhật cần cẩu, báo cáo chất lượng, nhân lực, cảnh báo an toàn - rồi mỗi sáng tóm gọn còn 3 dòng những gì cần lo. 82 tin nhắn rút về 3 dòng.",
    sourceLabel: "Reddit - u/Godzillaton",
    sourceUrl: "https://hermes-agent.nousresearch.com/docs/user-stories",
  },
  {
    icon: "🧠",
    title: '"Bản sao AI" thay bảng Excel cho một shop nhỏ',
    desc: 'Một chủ shop bán sản phẩm vật lý nhỏ dùng Hermes làm "Twin AI" - bản sao của chính mình, định nghĩa trong SOUL.md. Mục tiêu: đừng để bản thân thành nút thắt của mọi việc. Nó không chỉ "trả lời câu hỏi" mà "thay mình vận hành trong giới hạn rõ ràng".',
    sourceLabel: "Reddit - u/kenmazaika",
    sourceUrl: "https://hermes-agent.nousresearch.com/docs/user-stories",
  },
  {
    icon: "🧒",
    title: 'Một ông bố dựng "JARVIS" cho con 7 tuổi',
    desc: 'Một ông bố bỏ 9 ngày dựng "Kid Mode" trên Hermes cho con 7 tuổi: giao diện giọng nói, thẻ từ vựng, nhiệm vụ, huy hiệu cấp bậc, điều khiển nhà thông minh, và một đường dây nóng gọi thẳng về bố. Cách cho con làm quen AI vừa an toàn vừa vui.',
    sourceLabel: "Reddit - u/Exciting_Charity7304",
    sourceUrl: "https://hermes-agent.nousresearch.com/docs/user-stories",
  },
  {
    icon: "📚",
    title: "326 câu chuyện thật từ cộng đồng toàn cầu (và vẫn tăng)",
    desc: "Trang user stories chính chủ của Nous Research gom 326 câu chuyện thật từ Reddit, X, YouTube, Discord, blog... chia 15 nhóm chủ đề, mỗi câu đều dẫn về bài gốc. Tha hồ đào thêm ý tưởng cho công việc của bạn.",
    sourceLabel: "hermes-agent.nousresearch.com/docs/user-stories",
    sourceUrl: "https://hermes-agent.nousresearch.com/docs/user-stories",
    secondaryLabel: "github.com/aliaihub/awesome-hermes-usecases",
    secondaryUrl: "https://github.com/aliaihub/awesome-hermes-usecases",
  },
];

export interface Book {
  icon: string;
  color: string;
  title: string;
  desc: string;
  downloads: string;
}

export const libraryBooks: Book[] = [
  {
    icon: "🧑‍💼",
    color: "var(--teal)",
    title: "SOUL.md - Trợ lý văn phòng",
    desc: "Lịch sự, soạn email, nhắc lịch, tóm tắt tài liệu",
    downloads: "miễn phí",
  },
  {
    icon: "🏪",
    color: "var(--clay)",
    title: "SOUL.md - Kinh doanh 1 người",
    desc: "Trực fanpage, chăm khách, báo cáo sáng",
    downloads: "miễn phí",
  },
  {
    icon: "👨‍👩‍🧒",
    color: "var(--gold)",
    title: "SOUL.md - Trợ lý gia đình",
    desc: "Việc nhà, thực đơn, học hành, du lịch",
    downloads: "miễn phí",
  },
  {
    icon: "🌱",
    color: "#0E7C71",
    title: "Vòng lặp tự cải thiện",
    desc: "5 prompt nền + checklist 7 ngày - càng dùng càng hiểu bạn",
    downloads: "miễn phí",
  },
  {
    icon: "💬",
    color: "#0F766E",
    title: "100 prompt theo nghề",
    desc: "10 nghề, mỗi nghề 10 câu lệnh mẫu - copy dán là chạy",
    downloads: "miễn phí",
  },
  {
    icon: "⏰",
    color: "#7C3AED",
    title: "Skill - Bản tin sáng tự động",
    desc: "Prompt dựng bản tin mỗi sáng, kèm cách chỉnh theo gu",
    downloads: "miễn phí",
  },
];
